package com.musty.admin.domain.enumeration;

/**
 * The Generes enumeration.
 */
public enum Generes {
    ABSURDIST, ACTION, ADVENTURE, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL, HORROR, MYSTERY, PARANOID, PHILOSOPHICAL, POLITICAL, ROMANCE, SAGA, SATIRE, SCIENCE_FICTION, SOCIAL, SPECULATIVE, THRILLER, URBAN, WESTERN, SLICE_OF_LIFE
}
