package com.musty.admin.domain.enumeration;

/**
 * The Language enumeration.
 */
public enum Language {
    ARABIC, BENGALI, BULGARIAN, CHINESE, CROATIAN, DUTCH, ENGLISH, FINNISH, FRENCH, GERMAN, GREEK, HEBREW, HINDI, HUNGARIAN, ICELANDIC, ITALIAN, JAPANESE, KANNADA, KOREAN, MALAYALAM, MARATHI, NORWEGIAN, PERSIAN, POLISH, PORTUGUESE, PUNJABI, ROMANIAN, RUSSIAN, SPANISH, SWEDISH, TAMIL, TELUGU, TURKISH, UKRAINIAN
}
